apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  labels:
    app: hello-world
spec:
  type: LoadBalancer
  ports:
    - port: 5002
      targetPort: 3001
      protocol: TCP
  selector:
    app: hello-world